#Bot language/Язык ботов (en_US ru_RU uk_UA de_DE)
language: "en_US"
#Server IP/Айпи адрес сервера
ip: "ioann137.aternos.me:3888"
#Server Port/Порт сервера
port: 38884
#Bot password/Пароль ботов
password: "123412341234"
#Delay between connections (in ms)/Задержка между подключениями (в мс)
interval: 8000
#Minecraft version/Версия майнкрафта
version: "1.16.5"
